### ISSUE TITLE
Warnings from Xcode

### ISSUE THREAD

**Issue by volgin** [ryanheise/audio_session#10]
The plugin seems to work as expected, but Xcode shows a couple of warnings during the build. I post here in case you were not aware of them.

Warning 1

/users/andreivolgin/flutter/.pub-cache/hosted/pub.dartlang.org/audio_session-0.0.9/ios/Classes/AudioSessionPlugin.m:16:5: Expression result unused

```
@implementation AudioSessionPlugin {
    DarwinAudioSession *_darwinAudioSession;
    FlutterMethodChannel *_channel;
}

+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
    if (!plugins) {
        plugins = [NSHashTable weakObjectsHashTable];
    }
    [[AudioSessionPlugin alloc] initWithRegistrar:registrar]; // This line is marked as "Expression result unused"
}

```

Warning 2

/users/andreivolgin/flutter/.pub-cache/hosted/pub.dartlang.org/audio_session-0.0.9/ios/Classes/DarwinAudioSession.m:402:22: Incompatible pointer types assigning to 'NSNumber *' from 'NSNull * _Nonnull'

This is the relevant code:

```
    if (wasSuspended == nil) {
        wasSuspended = [NSNull null];
    }
```

**Comment by ryanheise** [comment]
Thanks for pointing this out. I've had a look at both and they should be easy enough to fix.

**Comment by ryanheise** [comment]
This is now fixed in the latest commit. (Although I probably won't do another release until at least some more features are added.)

**Comment by ryanheise** [comment]
This code has made it into the next release 0.0.10.
