### ISSUE TITLE
Can not play by speaker on iOS

### ISSUE THREAD

**Issue by SELiOTe** [ryanheise/audio_session#115]
`avAudioSessionCategory` set to `soloAmbient`, `avAudioSessionMode` is `defaultMode`, but always play audio from receiver

iPhone XR iOS 15.7
Flutter 3.13.9
just_audio: ^0.9.35
audio_session: ^0.1.17

**Comment by ryanheise** [comment]
I suggest asking on the Apple forums about the behaviour of their API (or on StackOverflow).

**Comment by SELiOTe** [comment]
> I suggest asking on the Apple forums about the behaviour of their API (or on StackOverflow).

Finally i found it's a bug by `record: ^5.0.1`, i set AudioSession globally, but `record` changed AudioSession each time

**Comment by ryanheise** [comment]
Ah, yes. You might consider pointing the `record` author to the audio_session README which explains the issue and why plugins sharing the audio session need to cooperate. audio_session obviously provides an easy solution to plugin authors, but alternatively the plugin author could just redesign its API to add an optional boolean parameter to its method that can be used to prevent it from overwriting the audio session.
