### ISSUE TITLE
`AVAudioSessionCategoryOptions`'s `contains` method takes `AVAudioSessionInterruptionOptions`. Maybe it should be `AVAudioSessionCategoryOptions`?

### ISSUE THREAD

**Issue by kainosk** [ryanheise/audio_session#117]
Thanks for great package ❤️ 

I found the code that may be a bug in [`darwin.dart`](https://github.com/ryanheise/audio_session/blob/93569121d72844a2b00023b005d21d97a82f30e5/lib/src/darwin.dart#L378).

```dart
  bool contains(AVAudioSessionInterruptionOptions options) =>
      options.value & value == options.value;
```

I think `AVAudioSessionCategoryOptions`'s `contains` method should take `AVAudioSessionCategoryOptions` itself. Is this a bug or intentional code?

Thanks you!

**Comment by ryanheise** [comment]
Well spotted! Would you be interested in submitting a pull request? Typically you would get credit for the fix by adding something to the CHANGELOG like this:

```
## 0.1.18

* Fix parameter type in AVAudioSessionCategoryOptions.contains (@kainosk).
```

**Comment by kainosk** [comment]
Thank you! I will try that!

**Comment by kainosk** [comment]
@ryanheise 

I have sent a PR for this issue (#118).

Thank you for giving a chance to send the PR ❤️

**Comment by kainosk** [comment]
Thank you for your review and merge! I'm happy to see the CHANGELOG 😄
