### ISSUE TITLE
Echo cancellation

### ISSUE THREAD

**Issue by torphix** [ryanheise/audio_session#124]
hi, thanks for the wicked package!

I cant find an option in audio session configuration to enable echo cancellation and am wondering if i'm missing it or if its named something different / not implemented

thanks

**Comment by ryanheise** [comment]
Hi, this package wraps the underlying native APIs for AudioManager and AVAudioSession. If you can find any method in either of those that you would like me to wrap, I can add it.

**Comment by torphix** [comment]
Here is the link for the android API: https://developer.android.com/reference/android/media/audiofx/AcousticEchoCanceler
for IOS there does not seem to be a straight forward API like android but I found this thread on the IOS developer forum which seems to achieve the same effect: https://forums.developer.apple.com/forums/thread/97679

**Comment by ryanheise** [comment]
That is not within the scope of this API. It's not within AudioManager. You might want to look at another plugin called just_audio which implements audio effects. If that doesn't suit your requirements, then you need a new plugin.
