### ISSUE TITLE
Execution failed for task ':audio_session:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by appu-sm** [ryanheise/audio_session#129]
While using this plugin in my flutter project i'm getting the error, i have seen somewhere to use compileSdkVersion less than 34, but my project requires version 34, is there a way to overcome this issue

```
 error: warnings found and -Werror specified

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audio_session:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

following is my flutter doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on Ubuntu 22.04.4 LTS 6.5.0-27-generic, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (installed)
[✓] VS Code (version 1.88.1)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by RomanSoviak** [comment]
@appu-sm did you solve this issue?

**Comment by ryanheise** [comment]
This should be fixed in the latest release.

**Comment by RomanSoviak** [comment]
@ryanheise thanks for the answer, when will it be done?🙂

**Comment by ryanheise** [comment]
By "latest release", I mean the one currently available. Are you already using 0.1.21 and still getting this error?

**Comment by RomanSoviak** [comment]
If somebody cannnot update lib to **0.1.21**: you can add this line of code to gradle.properties file:
`org.gradle.java.home=/Users/romansoviak/Library/Java/JavaVirtualMachines/corretto-11.0.22/Contents/Home
`

**Comment by dowlet-ode** [comment]
has anyone solved this issue?

**Comment by Omar-mhiri** [comment]
Add JAVA_HOME Globally (if you're linux user use sudo nano /etc/environment and nano ~/.bashrc )
then under android search for ./gradlew and use this: ./gradlew clean and ./gradlew build
if it does not work open android/gradle.properties, and add: your java path for exemple: "org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64" and then do ./gradlew sync
