### ISSUE TITLE
[Question] Can audio playback be started while app is in the background in IOS?

### ISSUE THREAD

**Issue by pamafe1976** [ryanheise/audio_session#130]
Hi,

I need a way to start playback of a short audio file while the app is in the background.
Is that possible for Android and IOS with this package?

Regards

**Comment by ryanheise** [comment]
I can't personally offer advice for individual use cases with this package, only that its purpose is to wrap whatever theAVAudioSession API does on iOS, and whatever the AudioManager API does on Android. You would probably need to research native solutions for Android and iOS first, and once you have a solution, look for a set of Flutter packages that provide the native APIs that you require.
