### ISSUE TITLE
java issue to even run the project

### ISSUE THREAD

**Issue by nokia6290** [ryanheise/audio_session#132]
Hello,

Can someone share their android gradle, specifically what java/gradle version this plugin requires to be compatible?

I'm running java openjdk 21 but its failing to run this plugin/project at all.

I know my setup java/gradle setup is correct as I'm running 20+ other flutter projects with no big issues but as soon as I add this plugin I have java issues and been trying to troubleshoot for the last two hours with no results.

Thank you.

edit: is the plugin using java 8 that was released in 2014?

**Comment by ryanheise** [comment]
The Java version in the plugin shouldn't prevent you from using a later version in your own project, although I'll update it to 14 to match Google's first party plugins. For an example, look in the example directory in this repo.

**Comment by ryanheise** [comment]
On the other hand, the template for new Flutter plugins still sets it to 1.8, so I don't see an immediate need to change this.
