### ISSUE TITLE
Notification stays open 

### ISSUE THREAD

**Issue by MichalPleban** [ryanheise/audio_session#133]
I am developing an application which allows the user to browse a collection of ebooks, pick one and then decide to read it or listen to it. It is also possible to switch between reading and listening. 

I am using this plugin together with just_audio to implement audiobook playback. During app unit, I create my own AudioHandler as a singleton and pass it to the init() function. Then, when the user starts an audiobook, upon calling AudioPlayer.play() the Android notification appears with the audio controls - so far so good. 

However, when the user finishes the audiobook or switches to the reader view, the Android notification persists even though it is no longer applicable. I am calling Audio player.dispose(), I also tried Audio session.setActive(false) but it makes no difference. The notification even persists when I reload the app from the Flutter debugger.

What is more perplexing is that in the Web version, it works - as soon as the AudioPlayer is disposed, the browser notification disappears. 

I can't see any API to programmatically hide the notification. So how do I get rid of it when the user is no longer on the audio player page?

**Comment by ryanheise** [comment]
This plugin does not manage notifications, but perhaps you meant audio_service.

**Comment by MichalPleban** [comment]
Ah of course. I pasted it in the wrong repository. I am sorry for the confusion.
