### ISSUE TITLE
"audio_session Plugin Fails to Respect minSdkVersion 23 After Migration to settings.gradle Plugin Management

### ISSUE THREAD

**Issue by vacating** [ryanheise/audio_session#145]
After migrating my Flutter project to the new plugin management method in settings.gradle, [ here ](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)  , the audio_session plugin doesn’t respect the global minSdkVersion 23. Despite correctly setting the minSdkVersion in the app/build.gradle, the plugin triggers API-level mismatch errors (e.g., using getId() which requires API 23). This issue forces me to manually enforce the minSdkVersion in settings.gradle.

### Steps to Reproduce:
1. Migrate to the new Flutter plugin management method.
2. Set minSdkVersion 23 in app/build.gradle.
3. Include the audio_session plugin.
4. Run the build and observe the API level mismatch error.

### _eror we got :_

`audio_session-0.1.21\android\src\main\java\com\ryanheise\audio_session\AndroidAudioManager.java:272: Error: Call requires API level 23 (current min is 16): android.media.AudioDeviceInfo#getId [NewApi]
                  "id", device.getId(),`

@ryanheise

**Comment by DurgeshSawantWYLD** [comment]
any solution for this, please help the android build is failing

**Comment by vacating** [comment]
@ryanheise  bruv where are u ? we got issue here

**Comment by pro100svitlo** [comment]
@DurgeshSawantWYLD @vacating 
while waiting for the hotfix you can specify in you dependencies the previous version:
```yaml
  audio_session: 0.1.20
```

Once that is done, make sure your `pubspeck.lock` file is the same version.

**Comment by khawjaahmad** [comment]
I am having a same issue and cannot move forward!

```
ryanheise/audio_session/AndroidAudioManager.java:272: Error: Call requires API level 23 (current min is 16): android.media.AudioDeviceInfo#getId [NewApi]
                  "id", device.getId(),
                               ~~~~~
```

**Comment by bbrockit** [comment]
Has anyone managed to fix this in a local repo or with config changes?  I'm getting the same error plus another sdk mismatch with audio_service, which is making calls requiring API 31.  I've been going in circles with different java versions, gradle versions, and gradle configs.

**Comment by GokulRajQuilt** [comment]
Is there a workaround for this issue. Should we import this or fork the package for short time and have the updated compile sdk version?

**Comment by pro100svitlo** [comment]
It seems that the whole `just_audio` family lacks support 😢

**Comment by ryanheise** [comment]
Apologies for the delay. Forks and pull requests are always welcome, as this is an open source project that is driven by contributions of many. I'll take a look at this in a moment, I just haven't been able to since my old computer broke down, and I've only just got my new system set up.

**Comment by ryanheise** [comment]
Locally, I've migrated the example to the new plugin management approach, but didn't get an error.

Would someone be able to provide a minimal reproduction project?

**Comment by ryanheise** [comment]
> * Migrate to the new Flutter plugin management method.
> * Set minSdkVersion 23 in app/build.gradle.
> * Include the audio_session plugin.
> * Run the build and observe the API level mismatch error.

Just to update again, applying these steps to audio_session/example does not reproduce the issue. I will therefore need someone to provide a link to a minimal reproduction project that I can run and see the error.

**Comment by ryanheise** [comment]
Changes have been pushed to `master`. Change `minSdk` to 23 in the example, run it, no error. If you can tell me how to reproduce the error, please do.

**Comment by ryanheise** [comment]
Today I was able to reproduce it by manually running the linter, and have published a new release which should fix the lints.
