### ISSUE TITLE
  Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.

### ISSUE THREAD

**Issue by fullflash** [ryanheise/audio_session#147]
Recommendation: remove package="com.ryanheise.audio_session" from the source AndroidManifest.xml: /Users/********/.pub-cache/hosted/pub.dev/audio_session-0.1.21/android/src/main/AndroidManifest.xml.

**Comment by ryanheise** [comment]
I don't think it means that the package attribute is no longer supported, I think it means that setting the namespace this way is no longer supported. `build.gradle` now contains code to set the namespace which I think satisfies this requirement without removing the package attribute from the manifest. Let me know if you find information to the contrary.
