### ISSUE TITLE
MacOS support issue?

### ISSUE THREAD

**Issue by KeithBacalso** [ryanheise/audio_session#149]
I maybe wrong here, but when I ran my app using macos desktop and tested it by someone callnig me in Messenger, but my audio recording did not pause... It worked in mobile android and ios tho.

**Comment by ryanheise** [comment]
audio_session wraps around the AVAudioSession API for iOS and the AudioManager API for Android. It doesn't do anything for other platforms, although if you are building a multiplatform app, audio_session will still allow you to link to audio_session for other platforms just so that it can compile, although it does nothing for those platforms.

**Comment by KeithBacalso** [comment]
> audio_session wraps around the AVAudioSession API for iOS and the AudioManager API for Android. It doesn't do anything for other platforms, although if you are building a multiplatform app, audio_session will still allow you to link to audio_session for other platforms just so that it can compile, although it does nothing for those platforms.

so you mean it doesnt work with desktop apps?: windows & macos

**Comment by ryanheise** [comment]
It doesn't do anything on those platforms.

**Comment by KeithBacalso** [comment]
> It doesn't do anything on those platforms.

I see, but here in pub.dev I can see that it supported it?
![image](https://github.com/user-attachments/assets/be0a7bb1-1fc1-458b-83a2-9a92632e5db1)

**Comment by ryanheise** [comment]
That means that it will compile with all of those platforms as I already explained. But you need to actually read the README page to see what the package actually does. As I have stated, the package will compile for all platforms, but it only does something for Android and iOS.
