### ISSUE TITLE
turn off music when in background

### ISSUE THREAD

**Issue by abraraltaf92** [ryanheise/audio_session#15]
I am using just_audio to play music in flutter app on android but its playing even when app is in background like I want to pause the music whenever I m outside of the app and continue when I m into the app again . I m unable to find any option. Any help ?

**Comment by abraraltaf92** [comment]
used Flame.bg.play()

**Comment by ryanheise** [comment]
Hi @abraraltaf92 audio_sesson isn't responsible for playing audio, but if you request it as a feature on just_audio, I will implement it. Note that you could already do this with just_audio by listening to flutter lifecycle events and then call the play/pause methods on receiving the appropriate events, however there may be benefits to providing this feature natively in just_audio in terms of responsiveness. That is, to get an immediate response from the player.
