### ISSUE TITLE
AVAudioSession mode

### ISSUE THREAD

**Issue by O-Sanjarbek-usoft** [ryanheise/audio_session#152]
AVAudioSession mode always returns AVAudioSessionMode.defaultMode

var mode = await AVAudioSession().mode;

I want to get the current audio mode but AVAudioSession.mode returns default even when the microphone is in use by another application.

**Comment by ryanheise** [comment]
That's because the underlying iOS API is returning `AVAudioSessionModeDefault` or null.

**Comment by O-Sanjarbek-usoft** [comment]
What if a device is on call mode? How can I detect whether an ios device is on phone/video call?
