### ISSUE TITLE
Feature Request: iOS Bluetooth Latency

### ISSUE THREAD

**Issue by samry** [ryanheise/audio_session#18]
Hey there!

I LOVE audio_session and just_audio - I use them both for our breathing app.

In our app, we have several breathing animations that are synced to audio.

This works great with wired speakers/headphones/phone speakers, but when the device is connected via Bluetooth/Airplay, the latency is large enough where we've had users start complaining.

While all Bluetooth devices have some latency, it varies relatively widely.

For this reason, I was wondering if it would be possible to implement a method to determine output device or output latency?

I already implemented in a little sample project just by creating a new method in DarwinAudiuoSession.m...

`- (void)getOutputLatency:(NSArray *)args result:(FlutterResult)result {
    result(@([[AVAudioSession sharedInstance] outputLatency]));
}`

It returns a double when on iOS devices that seem to be fairly accurate.

**Comment by ryanheise** [comment]
I have just added `outputLatency` and `inputLatency` (and a whole bunch of other missing methods) on git master, although it is completely untested. I would appreciate if you could let me know if it works for you.

**Comment by ryanheise** [comment]
These features have now been published in release 0.1.3 so I'll close this.
