### ISSUE TITLE
add some APIs from audio_service

### ISSUE THREAD

**Issue by nt4f04uNd** [ryanheise/audio_session#19]
i think you have considered this, but didn't have much time for this yet

i suggest that this plugin would provide a comprehensive API for any media session interactions, and thus some implementations from `audio_service` should be moved into here

* notification handling
* media button click handling
* (probably something else i missed)

with this we could make APIs more broad than we can do this in the `audio_service`, and at the same time it wouldn't lose anything and would still provide the same interface for such interactions, but by using the API from the `audio_session`

**Comment by ryanheise** [comment]
At the moment, the scope is AVAudioSession on Apple and AudioManager on Android. I would probably not consider anything outside of this cope for the time being.

Android has a few different kinds of "sessions":

1. You can request audio focus via the audio manager
2. You can become the active media session
3. You can also create a cast session

But these are not all the same thing and need not be in the same package. So for now I'd like to stick to the scope above.
