### ISSUE TITLE
Warning: AudioSessionPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by chplalex** [ryanheise/audio_session#24]
Hi,

![image](https://user-images.githubusercontent.com/63255416/114447921-9bdc9600-9bdb-11eb-90da-c600cde4bc76.png)

Compile with -Xlint:deprecation option:

![image](https://user-images.githubusercontent.com/63255416/114448301-0e4d7600-9bdc-11eb-97e0-cce6543112c2.png)

**Comment by ryanheise** [comment]
@lhartman1 's PR is merged which fixes this warning, and has been released in `0.1.1`.
