### ISSUE TITLE
Ability to play sound from the earpiece

### ISSUE THREAD

**Issue by jesusrp98** [ryanheise/audio_session#26]
Make possible to play audio from the device's earpiece (if available), rather than the main speaker.

This is related to a just_audio [issue](https://github.com/ryanheise/just_audio/issues/382).

**Comment by ma-pe** [comment]
This would be a great feature that I'd love to see in audio_session.

I personally would like to create a Spotify-alike selection menu of the available audio outputs (speaker, earpiece, connected bluetooth speaker, ...).

This could look something like this:

```
var outputRoutes = await session.getAvailableOutputRoutes();
// [AudioOutputRoute.Earpiece, AudioOutputRoute.Speaker, AudioOutputRoute.Bluetooth]
// ... show available output routes

session.setOutputRoute(AudioOutputRoute.Earpiece);
```

There is a plugin with a similar approach: https://github.com/yungzhu/flutter_audio_manager
Unfortunately it is not null safe and there is not possibility to get available outputs.

**Comment by ryanheise** [comment]
The goal is to eventually expose all of the Android `AudioManager` and iOS `AVAudioSession` APIs, and currently Android is a bit behind. I am trying to at least get the Android side filled out this weekend.

On the iOS side, the API is more complete but actually the parts yet to do are exactly the parts you require. I won't have time to finish that side this week, but if anyone would like to help, pull requests are most welcome. However, from memory some non-trivial decisions needed to be made about how to implement platform method calls on nested objects. I have at least provided some commented-out code in the plugin if someone would like to take a look at it help uncomment/implement the needed parts.

**Comment by ryanheise** [comment]
I've just committed to `master` an update to the Android side, adding 35 additional methods to `AndroidAudioManager`.

While I won't be able to finish the iOS side this weekend, I can at least take a look at maybe implementing a couple of the relevant methods.

**Comment by ryanheise** [comment]
I've just added some iOS support for audio routes/ports. It is completely untested, but you are welcome to try it and let me know if there's anything I need to fix.

Currently the new functionality is all platform specific code added to the `AndroidAudioManager` and `AVAudioSession` classes respectively. If there is any common functionality that can be extracted from both of these classes, that can eventually be made available as convenience methods in `AudioSession`.

**Comment by ryanheise** [comment]
These features are now released in 0.1.3.

**Comment by ryanheise** [comment]
I'll close this, but if you discover an issue let me know and I'll reopen.

**Comment by jesusrp98** [comment]
@ryanheise @ma-pe It's not very clear to me how to implement this feature on both iOS and Android.

Could you please share some example code or snippets?
Thanks!
