### ISSUE TITLE
Ducking Spotify/music playesr

### ISSUE THREAD

**Issue by ninest** [ryanheise/audio_session#27]
I'm trying to make an app similar to Google Maps where some audio should duck Spotify/any music player's output temporarily on Android.

```dart
androidAudioFocusGainType: AndroidAudioFocusGainType.gainTransientMayDuck,
```
but this doesn't work for Spotify, while it does work with my local music player (Poweramp). However, once the audio **is ducked, it does not go back to its full volume even after the audio my app plays is complete**.

How do I achieve a Google Maps like effect with my audio? I wonder if `androidWillPauseWhenDucked` has anything to do with it?

I also tried

```dart
androidAudioAttributes: const AndroidAudioAttributes(
	usage: AndroidAudioUsage.assistanceNavigationGuidance,
),
```

but it had the same issues

**Comment by ryanheise** [comment]
To allow the music player to return to full volume, do you call `audioSession.setActive(false)`?

I'm not sure about the Spotify behaviour, do you know if Spotify respects the navigator in Google maps? If so that gives some hope that you can experiment with different options in addition to the one you've set. For example for the audio attributes you could set the content to speech, and you could also set the gain type to transient.

**Comment by ryanheise** [comment]
Release 0.1.3 now exposes pretty much all of the AVAudioSession and AudioManager capabilities so if there is a solution to your problem in native code, the corresponding solution should work in this plugin.

**Comment by ryanheise** [comment]
I can't advise on how to use Apple's API to the desired effect, however this plugin exposes all of the iOS AVAudioSession APIs pretty much as a mirror image of Apple's API, so if you need help using Apple's API I would suggest searching on StackOverflow for questions relating to AVAudioSession on iOS, and if you do not find the answer you're looking for, you can ask the community on StackOverflow a new question as per your needs.

**Comment by ryanheise** [comment]
> * If your app provides occasional spoken audio, such as in a turn-by-turn navigation app or an exercise app, you should also set the [**interruptSpokenAudioAndMixWithOthers**](https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions/1616534-interruptspokenaudioandmixwithot) option.

As I just said, this plugin is a direct mirror of the Apple API. This plugin also provides `interruptSpokenAudioAndMixWithOthers` and it is defined in the same place in the API. You can just browse this plugin's API documentation and it should be easy enough to find it based on the expected API names.

> Note that ducking begins when you activate your app’s audio session and ends when you deactivate the session. If you clear this option, activating your session interrupts other audio sessions.

If you are asking how to use Apple's API, I just said I can't answer that. If you are saying this plugin is missing an API that is necessary to do what you're trying to do, you can make a feature request. or if you're saying this plugin has the API you need, but it's behaviour is different from the underlying Apple API's behaviour, you can report the bug. But I can't advise on how to use Apple's API.

**Comment by adiPumba** [comment]
@ryanheise 
What is the code to end a session with audio_session?
Just to be sure, is this the correct line: `audioSession.setActive(false)` ?

**Comment by ryanheise** [comment]
`audioSession.setActive` when on iOS will redirect to `AVAudioSession().setActive` and you can consult Apple's documentation for what that method does and what its return value is. I can't personally advise you on how to achieve the desired behaviour, but you can either consult Apple's API documentation or ask about Apple's API on StackOverflow.
