### ISSUE TITLE
Currently playing info?

### ISSUE THREAD

**Issue by shinyford** [ryanheise/audio_session#3]
Hi

I'm looking for a Flutter plugin that allows my app to display information about what's currently playing via the speaker or connected bluetooth devices - artist, track, cover art, that sort of thing. (Potentially some limited control too - next track, pause, resume; but not necessarily.)

audio_session looks like it gets close to what I'm looking for, but (if I've read it correctly) focuses on the app that's running rather than system-wide audio that might come from players currently backgrounded.

I'm pretty new to this low-level side of audio, so I wondered if you'd be able to tell me if you thought that kind of information was potentially available, and if so whether audio_session was an appropriate package in which to surface them for Flutter consumption? If you think it is, I'll happily fork and try to get it to work.

Thanks for any insights - and apologies if this is exactly what audio_session already provides, and I'm too ignorant about the iOS/Android audio internals to tell.

Cheers

Nic Ford

**Comment by ryanheise** [comment]
It sounds like this would best be a fit for audio_service. I know the distinction between APIs can be a bit confusing, but:

* audio_session is more about querying the audio hardware, requesting permission to use the audio hardware, and letting the OS know how your app intends to use the audio hardware and interact with other audio apps.
* audio_service deals with a different set of APIs that involve the now playing info, controlling the audio (play pause, next track), and playing audio in the background.

That said, audio_service was designed to help you write the app that is actually playing the music and showing the controls and now playing info. It also includes an API to allow you to connect to an existing audio service that is running, but it currently assumes that you are connecting to your own app. This could be extended such that you could connect to other apps.

**Comment by shinyford** [comment]
Thanks for the feedback - really interesting. Okay, I'll dig into audio_service to see if I can work out what needs to be done, and send you a PR if and when I make progress. Cheers!

**Comment by ryanheise** [comment]
Sounds good! I'd suggest creating a feature request there before working on your pull request where we can discuss the issue.
