### ISSUE TITLE
Android 5 ExoPlayer crash

### ISSUE THREAD

**Issue by nicoroy2561** [ryanheise/audio_session#33]
Hi, the recent update 0.1.4 broke my app on old Android devices, but was later fixed by 0.1.5 so now it is all good.
To investigate the issue I set up an Android 5 emulator (didn't have it before so would not know wether it used to work on versions lower than 0.1.4 or not), and it turns out that (after the initial issues were fixed, upgrading to 0.1.5), the plugin crashes upon trying to play some audio.

```
...
I/OMXClient(20748): Using client-side OMX mux.
E/AudioTrack(20748): AudioFlinger could not create track, status: -12
E/AudioTrack-JNI(20748): Error -12 initializing AudioTrack
E/android.media.AudioTrack(20748): Error code -20 when initializing AudioTrack.
E/ExoPlayerImplInternal(20748): Playback error
E/ExoPlayerImplInternal(20748):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [2, 44100]), format_supported=YES
E/ExoPlayerImplInternal(20748):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal(20748):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(20748):       at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal(20748):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(20748):   Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(44100, 12, 44100)
E/ExoPlayerImplInternal(20748):       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:1999)
E/ExoPlayerImplInternal(20748):       at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:821)
E/ExoPlayerImplInternal(20748):       at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:626)
E/ExoPlayerImplInternal(20748):       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:699)
E/ExoPlayerImplInternal(20748):       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:630)
E/ExoPlayerImplInternal(20748):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1854)
E/ExoPlayerImplInternal(20748):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:824)
E/ExoPlayerImplInternal(20748):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:947)
E/ExoPlayerImplInternal(20748):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477)
E/ExoPlayerImplInternal(20748):       ... 3 more
E/AudioPlayer(20748): TYPE_RENDERER: AudioTrack init failed 0 Config(44100, 12, 44100)
...
```

I see this message repeated multiple times (3?) every time my app tries to play some audio (simple .mp3 files).

Is there anything that can be done about this?

**Comment by ryanheise** [comment]
This error seems to be for just_audio rather than audio_session. It's the following helpful?

https://exoplayer.dev/supported-devices.html

**Comment by nicoroy2561** [comment]
@ryanheise thank you very much for the prompt response!
The paragraph on emulators answered my question:

`
Emulators - Some Android emulators do not properly implement components of Android’s media stack, and as a result do not support ExoPlayer. This is an issue with the emulator, not with ExoPlayer. Android’s official emulator (“Virtual Devices” in Android Studio) supports ExoPlayer provided the system image has an API level of at least 23. System images with earlier API levels do not support ExoPlayer. The level of support provided by third party emulators varies. Issues running ExoPlayer on third party emulators should be reported to the developer of the emulator rather than to the ExoPlayer team. Where possible, we recommend testing media applications on physical devices rather than emulators.
`

In hindsight, I should have checked myself with the ExoPlayer website.
Thanks a lot! Please keep up the good work.
