### ISSUE TITLE
Add convenience methods to switch between speaker and headphone

### ISSUE THREAD

**Issue by ryanheise** [ryanheise/audio_session#37]
Some information for the Android side:

https://stackoverflow.com/questions/22770321/android-switching-audio-between-bluetooth-and-phone-speaker-is-inconsistent

**Comment by wijesijp** [comment]
Hi @ryanheise any where you able to find out how to do this?

I have similar issue on iOS.

I thought following would change it . But it is giving me an error.
I am also seeing only the speaker option so I assume there must be a different way to do this.

await AVAudioSession().overrideOutputAudioPort(AVAudioSessionPortOverride.speaker);

**Comment by ryanheise** [comment]
I think there are several answers on StackOverflow for how to do this and I would encourage those interested in this feature to first do a search on StackOverflow. Please share below what you find as I will collect the ideas and techniques that you share and ultimately consider making them into a convenience method.

**Comment by ryanheise** [comment]
Closing in favour of #39 .
