### ISSUE TITLE
Compatibility with τ-Sound

### ISSUE THREAD

**Issue by Larpoux** [ryanheise/audio_session#44]
Hi @ryanheise ,

This is not an issue, but just a congratulation for this plugin idea.

When I began to work on [flutter_sound](https://flutter-sound.canardoux.xyz/readme.html), I had a terrific idea. Something really great : implement the concept of audio-session. Each recorder or player will have its own session. It was a brilliant idea ... until I realized that iOS can manage only one session per App.  But I realized that too late, and the flutter_sound API implements the audio-session concept, but works very surprisingly when the App opens several players or recorders.

Then I am actually rewriting the [τ-Sound](https://tau.canardoux.xyz/readme.html) API, and try to handle correctly the session concept.
But I am realizing that it could be a problem if the App uses also other plugins like just_audio.

And now I am discovering this plugin. Federating all audio-plugins sessions is a bright idea.
I will certainly do a dependency to audio-session from [τ-Sound](https://tau.canardoux.xyz/readme.html).

Thanks

**Comment by ryanheise** [comment]
Hi @Larpoux , thanks for the compliment. I agree it's a widespread issue, and so it's a plugin somebody would have eventually had to create given the situation of apps wanting to incorporate multiple audio plugins into the same app. It might be accidental I am the one to create it :-)

Anyway, I shall close the issue.
