### ISSUE TITLE
NSMicrophoneUsageDescription when compile out the option with the pod file ios

### ISSUE THREAD

**Issue by remyut** [ryanheise/audio_session#47]
Hi,

I am having some issue regarding the iOS NSMicrophoneUsageDescription. 

I am using the flutter TTS plugin with audio session to duck the background sounds when the TTS plugin is talking.

` initAudioSession() async{
    session = await AudioSession.instance;
    await session.configure(AudioSessionConfiguration(
      avAudioSessionCategory: AVAudioSessionCategory.playback,
      avAudioSessionCategoryOptions: AVAudioSessionCategoryOptions.duckOthers,
      avAudioSessionMode: AVAudioSessionMode.defaultMode,
      avAudioSessionRouteSharingPolicy: AVAudioSessionRouteSharingPolicy.defaultPolicy,
      avAudioSessionSetActiveOptions: AVAudioSessionSetActiveOptions.none,
      androidAudioAttributes: const AndroidAudioAttributes(
        contentType: AndroidAudioContentType.speech,
        flags: AndroidAudioFlags.none,
        usage: AndroidAudioUsage.media,
      ),
      androidAudioFocusGainType: AndroidAudioFocusGainType.gainTransientMayDuck,
      androidWillPauseWhenDucked: true,
    ));`

I do not use the microphone at all (Unless the duck attribute uses the microphone).
But I have no microphone permission whatsoever enable or iOS or Android.

 I have edited my pod file to be as suggested (to compile out the mic option):

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)    
    target.build_configurations.each do |config|
       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
       config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'AUDIO_SESSION_MICROPHONE=0'
      ]
      end
  end
end

But I am still getting ITMS-90683: Missing Purpose String in Info.plist - The app's Info.plist file should contain a NSMicrophoneUsageDescription from Apple.

The version of audio_session is the latest: 0.1.6+1

My flutter doctor -v output: 
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-SG)
    • Flutter version 2.5.3 at /Users/remy/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/remy/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • iPad (9th generation) (mobile) • 7D9BF1E7-CF23-4185-A364-031987D00AD3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)                   • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!

Any advice?

Thanks a lot
Remy

**Comment by ryanheise** [comment]
> post_install do |installer|
> installer.pods_project.targets.each do |target|
> flutter_additional_ios_build_settings(target)
> target.build_configurations.each do |config|
> config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
> config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
> '$(inherited)',
> 'AUDIO_SESSION_MICROPHONE=0'
> ]
> end
> end
> end

It's a bit difficult to tell just from looking at that. I don't know if you actually formatted it that way and what else is in your file, or whether you edited the correct file, etc.

**Comment by remyut** [comment]
Hi ryanheise,

Sorry the indentation did not work well.

I will explain a bit more. 
I need to duck some other sound while playing my sound. So for that I use Audio_session which does a pretty good job on Android.

I use the following code to achieve the ducking:
`
initAudioSession() async{
    session = await AudioSession.instance;
    await session.configure(AudioSessionConfiguration(
      avAudioSessionCategory: AVAudioSessionCategory.playback,
      avAudioSessionCategoryOptions: AVAudioSessionCategoryOptions.duckOthers,
      avAudioSessionMode: AVAudioSessionMode.defaultMode,
      avAudioSessionRouteSharingPolicy: AVAudioSessionRouteSharingPolicy.defaultPolicy,
      avAudioSessionSetActiveOptions: AVAudioSessionSetActiveOptions.none,
      androidAudioAttributes: const AndroidAudioAttributes(
        contentType: AndroidAudioContentType.speech,
        flags: AndroidAudioFlags.none,
        usage: AndroidAudioUsage.media
      ),
      androidAudioFocusGainType: AndroidAudioFocusGainType.gainTransientMayDuck,
      androidWillPauseWhenDucked: true,
    ));
` 

The real problem is on iOS where the app validator complains about the NSMicrophone. 

I follow the iOS setup from: [https://pub.dev/packages/audio_session]
My pod file is attached as pod file.zip.
[Podfile.zip](https://github.com/ryanheise/audio_session/files/7533253/Podfile.zip)

But I am still getting the same error from Applet that prevents me to deploy my app.

I am seeking for some advice
Thanks
Remy

**Comment by ryanheise** [comment]
Please search "GitHub markdown syntax" to learn how to format.

```
code {
  with indentation
}
```

**Comment by ryanheise** [comment]
Fenced code blocks:

https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

**Comment by ryanheise** [comment]
Can you format your code with indentation please?

**Comment by remyut** [comment]
Sure here it is:

the audio-session code for ducking:
``` {

 initAudioSession() async{
    session = await AudioSession.instance;
    await session.configure(AudioSessionConfiguration(
      avAudioSessionCategory: AVAudioSessionCategory.playback,
      avAudioSessionCategoryOptions: AVAudioSessionCategoryOptions.duckOthers,
      avAudioSessionMode: AVAudioSessionMode.defaultMode,
      avAudioSessionRouteSharingPolicy: AVAudioSessionRouteSharingPolicy.defaultPolicy,
      avAudioSessionSetActiveOptions: AVAudioSessionSetActiveOptions.none,
      androidAudioAttributes: const AndroidAudioAttributes(
        contentType: AndroidAudioContentType.speech,
        flags: AndroidAudioFlags.none,
        usage: AndroidAudioUsage.media,
      ),
      androidAudioFocusGainType: AndroidAudioFocusGainType.gainTransientMayDuck,
      androidWillPauseWhenDucked: true,
    ));

  }
}
```

and my pod file (iOS/podfile):

```{
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
	config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'AUDIO_SESSION_MICROPHONE=0'
      ]
      end
  end
end

}```

I might be doing something wrong for still having the apple warning while submitting my app. 
For the time being I have add the string in the Info.plist saying that 'this app do not use the microphone'

Thanks a lot for your help
Remy

**Comment by ryanheise** [comment]
Well now that I can see your indentation, I can see that it is wrong. Near the end:

```
      end
  end
end
```

**Comment by remythales** [comment]
I will investigate the format of a POD file. But so far if the format was wrong it would have not compiled.
I have 3 'do' so I close them with 3 'end'

**Comment by remyut** [comment]
I will investigate the format of a pod file. But so far if. the format was wrong it would have not compiled. I have 3 'do' so I close them with 3 'end'...

**Comment by ryanheise** [comment]
Yes you should close all 3 of them. But you should also fix your indentation which is what I'm pointing out. By the way, indentation means the amount of spaces at the beginning of each line, not he number of 'end' keywords that you have.

**Comment by remyut** [comment]
Hi Ryanheise,
Thanks for your help, the indentation in the Podfiles was wrong. I fixed it by selecting all lines in the Podfiles and hit Control+I, my indentation changed and now apple is accepting my app without specifying the usage for the microphone

Thanks a lot to point the indentation out
Remy
