### ISSUE TITLE
google.bintray bad gateway

### ISSUE THREAD

**Issue by telmedola** [ryanheise/audio_session#49]
Hi, i tray to download from maven, but returns http 502 from url https://google.bintray.com/exoplayer/androidx/media2/media2-common/maven-metadata.xml inside your project.
I research and found this message in the site: https://status.bintray.com/ 
"Thanks for supporting Bintray! This service has now been sunset." in: Dec 1, 15:04 UTC

**Comment by ryanheise** [comment]
This plugin does not have a dependency on exoplayer. Are you sure you've got the right plugin here?

**Comment by ryanheise** [comment]
Can you include the whole error message for context so that it shows clearly this is an issue with audio_session?

```
Of course, quote the output like this
```

Can you also mention what other plugins you're using in your `pubspec.yaml`? Almost certainly it's one of those other plugins that is using exoplayer. I'm also not sure where the bintray reference is coming from. There is no bintray referenced anywhere inside of audio_session.

**Comment by haoXu1990** [comment]
Thanks reply
i'm checking all the plugins from pubspec.yaml。

**Comment by ryanheise** [comment]
Feel free to copy and paste your dependencies below. And also share the full context of the error message as requested above.

**Comment by telmedola** [comment]
Hi, so...
I don't use audio_session directly, but assets_audio_player which uses audio_session.
Here is the build output:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processReleaseResources'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve androidx.media2:media2-common:[1.1.3].
     Required by:
         project :app > project :audio_session > androidx.media2:media2-session:1.1.3
      > Failed to list versions for androidx.media2:media2-common.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/androidx/media2/media2-common/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/androidx/media2/media2-common/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/androidx/media2/media2-common/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

in my pubspec.yaml does not have the direct audio_session

**Comment by ryanheise** [comment]
I don't think assets_audio_player uses audio_session:

https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/pubspec.yaml

But let's say some other plugin in your project transitively depends on audio_session, the build process will try to merge everything and will run into a problem because assets_audio_player is using an out-of-date gradle repository called jcenter. You should report this issue with that project.

**Comment by telmedola** [comment]
Right, thanks.
Despite not appearing as a dependency, when I commented on assets_audio_player, the error didn't happen. That's why I thought it was a direct dependency.

I'll try another way.
Thank you for your help

**Comment by ryanheise** [comment]
I don't think there is another way besides reporting the bug to assets_audio_player so that it doesn't use a deprecated repository.

**Comment by telmedola** [comment]
Right.
I will do that too

Thanks.

**Comment by telmedola** [comment]
Well, i figured out:
1 - open the folder "android" in separated window of android studio.
2 - zzz...zzzz.... maven execution about 20 minutes
3 - upgraded my maven of 3.5.4 to 7.0.4, as sugest ed of android studio. 
4 - zzz...zzzzz... maven execution about 30 minutes.
5 - closed the windows of android project and open my flutter application.
6 - flutter build apk   ..zzz....zzzzz... waiting about 20 minutes
7 - change same dependencies with incompatibilits wiht new gradle.
8 - abracadabra: and everthing worked. 
🤷‍♂️

**Comment by ryanheise** [comment]
> 6 - flutter build apk ..zzz....zzzzz... waiting about 20 minutes

I suspect that waiting time is Gradle trying to merge your plugins in a number of different ways to see which way works, and I think that takes longer when packages in your dependencies use different repositories or have different versions of the same dependency etc.

**Comment by ryanheise** [comment]
In any case, I assume the issue can be closed.
