### ISSUE TITLE
How to use this without Cocoapods?

### ISSUE THREAD

**Issue by CiriousJoker** [ryanheise/audio_session#50]
How can I used this plugin in a project without CocoaPods?

Steps to reproduce:
1. `flutter create . --platforms ios`
2. Add the plugin
3. `cd ios`
4. `pod deintegrate`
5. Open XCode and run the app

<img width="1196" alt="Bildschirmfoto 2022-01-11 um 10 05 55" src="https://user-images.githubusercontent.com/16866223/148912986-6d9d1a4c-e8da-41f1-8261-5a8cb84ff3fe.png">

**Comment by ryanheise** [comment]
No, because you can't use "Flutter" without CocoaPods. It's a required component in Flutter's build process.

**Comment by CiriousJoker** [comment]
Oh, in that case I must have misunderstood the instructions for the Firebase plugins. They refer you to install them via Swift, but CocoaPods already installs all pods (including Firestore etc.) via `flutter_install_all_ios_pods`, so I thought I was supposed to deintegrate CocoaPods.
