### ISSUE TITLE
Upgrade Android dependency to media2-session 1.2.0

### ISSUE THREAD

**Issue by ryanheise** [ryanheise/audio_session#51]
The new version of this dependency requires upgrading the compile SDK version to 31, so unfortunately this would be a breaking change. I'll hold off until just_audio and audio_service are prepared for a major version bump.

**Comment by towynlin** [comment]
Looks like this issue was resolved in commit https://github.com/ryanheise/audio_session/commit/2631f7aab81d581e10dd7947264dbe07c015f650 and may be closed.

**Comment by ryanheise** [comment]
Thanks for the reminder, yes this ought to be closed.
