### ISSUE TITLE
Recording works when using Airpod Pros, but not when using Airport 2nd or 1st gen

### ISSUE THREAD

**Issue by ericadu** [ryanheise/audio_session#57]
First of all, I apologize if this is actually a [`flutter_sound` issue](https://github.com/Canardoux/flutter_sound/issues/885). I've cross posted there for support as well, but haven't gotten answer 🙏🏼

I'm curious if anyone else has issues with recording to stream on a iOS device while pairing with a Bluetooth headset. The behavior we're seeing is that we are able to when using the newest Airpod Pros on physical iOS 15.4.x devices, but it does not work (does not record at all, we're seeing empty bytes) when using any other bluetooth headset.

Here is the config I'm using:

```
    await session.configure(AudioSessionConfiguration(
      avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
      avAudioSessionCategoryOptions:
          AVAudioSessionCategoryOptions.allowBluetooth |
              AVAudioSessionCategoryOptions.allowBluetoothA2dp |
              AVAudioSessionCategoryOptions.defaultToSpeaker,
      avAudioSessionMode: AVAudioSessionMode.spokenAudio,
      avAudioSessionRouteSharingPolicy:
          AVAudioSessionRouteSharingPolicy.defaultPolicy,
      avAudioSessionSetActiveOptions: AVAudioSessionSetActiveOptions.none,
      androidAudioAttributes: const AndroidAudioAttributes(
        contentType: AndroidAudioContentType.speech,
        flags: AndroidAudioFlags.none,
        usage: AndroidAudioUsage.voiceCommunication,
      ),
      androidAudioFocusGainType: AndroidAudioFocusGainType.gain,
      androidWillPauseWhenDucked: true,
    ));
``` 

I've tried a couple of different things, including setting the session once in the app, as well as another variation where I set the session after I open the recording session, and another variation where I set the session config after I start recording.

Any direction would be helpful as I'm pretty stuck. I also haven't found another usable/maintained flutter package that has the record to stream functionality I need 😅

Thank you in advance!

**Comment by ryanheise** [comment]
Since audio_session is a direct mirror of the underlying native APIs, you might actually have better success finding a working configuration by looking on StackOverflow. Questions specifically about iOS will also directly apply to this plugin because the API one-to-one corresponds to that.

**Comment by ryanheise** [comment]
As for flutter_sound, I am not exactly familiar with what it is doing under the hood, so if it is an issue with timing, where flutter_sound is setting AVAudioSession parameters and audio_session is also setting these parameters, and whoever sets them last "wins", then I can't personally give you an answer on that unfortunately.

**Comment by ericadu** [comment]
Got it, will try StackOverflow specifically around iOS. Closing this. Thanks!
