### ISSUE TITLE
getMode() always returns 0

### ISSUE THREAD

**Issue by nessblo** [ryanheise/audio_session#59]
AndroidAudioManager's getMode() always returns 0

I want to get the current audio mode but _manager.getMode()  returns 0 even when the microphone is in use by another application.

**Comment by ryanheise** [comment]
Does this also happen with the latest code on `master`?

**Comment by nessblo** [comment]
I'm having trouble using latest code on master

Because audio_service 0.18.4 depends on audio_session ^0.1.6+1 and no versions of audio_service match >0.18.4 <0.19.0, audio_service ^0.18.4 requires audio_session from hosted.
So, because empire_afrique depends on both audio_session from git and audio_service ^0.18.4, version solving failed.

I have also tried master, minor and major code from audio_service git, but still getting errors.

**Comment by ryanheise** [comment]
I'm confused. So are you unable to try master, or are you unable to try master?  If the latter, use a dependency override in your pubspec.

**Comment by nessblo** [comment]
Yes I am a beginner in fact, finally I had to copy the code of the 3 updated files and paste in the local files and there it works very well; also setMicrophoneMute didn't work, but everything works perfectly now.

Thanks very much

**Comment by ryanheise** [comment]
The fix has now been released in 0.1.7 so I'll close this.

**Comment by nessblo** [comment]
Thanks you
