### ISSUE TITLE
devicesChangedEventStream does not broadcast AudioDevice Details on iOS 15

### ISSUE THREAD

**Issue by Colton127** [ryanheise/audio_session#63]
Flutter doctor: (I don't use android on Mac)
```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale
    en-US)
[!] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.68.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

Testing on a physical iPhone X running iOS 15.2 with generic wireless bluetooth earbuds

To replicate, active audio_session and listen to devicesChangedEvent
```
  void listen() {
    _audioSession.devicesChangedEventStream.listen((devicesChangedEvent) {
      print('AudioSession: Listener called with event. Added: ${devicesChangedEvent.devicesAdded}. Removed: ${devicesChangedEvent.devicesRemoved}');
    });
  }
```

**The headphones are successfully detected by session.getDevices**

**When headphones are connected or disconnected, the stream is called. However, no devices are listed.**

**Comment by ryanheise** [comment]
Would you be able to include the output for each event?

**Comment by Colton127** [comment]
> Would you be able to include the output for each event?

Hi,

The listener is called when a device is added or removed, but both devicesAdded and devicesRemoved return empty.

If you call session.getDevices after the listener is called, the updated device list appears successfully.

I'll do more testing tomorrow.

Thank you

**Comment by pioneerwalk** [comment]
Thanks for reporting the problem and confirming it.

I run into the same problem.
However, listeners are not called. (Even after adding Bluetooth, the listener is not called, so the reply is not void either)
I would like to know if this problem can be solved or if there is another solution.

I get the following output only when I start playback with just_audio (^0.9.29).
```dart
flutter: devices: {AudioDevice(id:Built-In Microphone,name:iPhone microphone,isInput:true,isOutput:false,type:AudioDeviceType.builtInMic), AudioDevice(id:Built-In Receiver,name:receiver,isInput:false,isOutput:true,type:AudioDeviceType.builtInEarpiece)}
```

**Comment by sgowda97** [comment]
Hi,

core.dart#96 should be declared outside the stream I think. I tried this and it worked, gives you the list of added/removed devices.

**Comment by ryanheise** [comment]
Oh you're right, that line is clearly a mistake. I will take a careful look tonight.

**Comment by ryanheise** [comment]
OK, so that line was intended to be moved down one line:

```dart
      final currentRoute = await _avAudioSession!.currentRoute;
      final previousRoute = _previousAVAudioSessionRoute ?? currentRoute;
      _previousAVAudioSessionRoute = currentRoute;
```

Can you test the above and let me know if it works for you?

**Comment by ryanheise** [comment]
Or easier, I have just pushed this commit to `master`. You can simply clone the latest code and see how it goes.

If all is well, I'll publish the next release.

**Comment by sgowda97** [comment]
Sure. I'm testing it out as we speak. Let me get back to you.

**Comment by sgowda97** [comment]
@ryanheise Works as expected! Thanks.

**Comment by ryanheise** [comment]
This has now been released to pub.dev as version 0.1.11. Thanks @sgowda97 for pointing out the line where I had made the mistake, and thanks @Colton127 for originally reporting the issue.

**Comment by fullflash** [comment]
tested at version 0.1.13
empty set no device details.
[log] AudioSessionManagerImpl.Devices added: {}
[log] AudioSessionManagerImpl.Devices removed: {}
