### ISSUE TITLE
Microphone is in used or not

### ISSUE THREAD

**Issue by naeem-shah** [ryanheise/audio_session#74]
Is it possible to check microphone state. I want to check is Microphone is available for recording or not.

I want to show user a message if microphone is already in used by another application "Microphone is Already in used"

**Comment by ryanheise** [comment]
Hi @naeem-shah , since this package just exports the original iOS and APIs (AVAudioSession and AudioManager), it will probably be better to ask two separate questions on StackOverflow to the iOS and Android developer communities.

**Comment by jamescardona11** [comment]
@naeem-shah did you solve this?

**Comment by ryanheise** [comment]
Again, I recommend asking on StackOverflow, or searching for the answer on StackOverflow. These APIs are a direct mirror of the native APIs, and so when searching on StackOverflow, you will find it helpful to search for questions relating to the native APIs directly.
