### ISSUE TITLE
Request for additional AudioSessionConfiguration recipe.

### ISSUE THREAD

**Issue by FluffyBunniesTasteTheBest** [ryanheise/audio_session#85]
Hello @ryanheise ,

Thank you for providing audio_session.

Would it be possible to add an `AudioSessionConfiguration` recipe that keeps other media players running (ideally without changing their volume)?

One case where this would be useful are apps that run in background and periodically play some short audio clips to notify the user about some actions to take. For this kind of apps, it would be great if other media players would just continue playback as if nothing happened.

**Comment by ryanheise** [comment]
Even if this were possible on iOS, I would not want to add it as a standard recipe. I'd rather provide recipes for the primary use cases, and then for anything more advanced, users can use the necessary low level APIs to support their specific use case.

To understand more about why iOS behaves the way it does, I would advise searching for similar questions on StackOverflow.
