### ISSUE TITLE
Toogling audio output between earpiece and speaker

### ISSUE THREAD

**Issue by mmartinalo** [ryanheise/audio_session#9]
## Context

I am developing a mobile application that plays audios with the packages [just_audio](https://pub.dev/packages/audio_service) and [audio_service](https://pub.dev/packages/audio_service). I am trying to add a feature using the proximity sensors of the device so that every time the user brings the mobile closer to the ear, the audio is played from the earpiece

## Dependencies
-  audio_service: 0.15.2
-  just_audio: 0.5.5
-  audio_session: 0.0.9

## My current state

When the service starts I configure the AudioSession as following
~~~dart
    final session = await AudioSession.instance;
    await session.configure(AudioSessionConfiguration.music());
~~~

And I have a custom action when the proximity sensor is actived
~~~dart
  final session = await AudioSession.instance;
  final AudioSessionConfiguration currentConfiguration = session.configuration;
  await session.configure(
    session.configuration.copyWith(
      androidAudioAttributes: AndroidAudioAttributes(
        usage: AndroidAudioUsage.voiceCommunication,
        flags: currentConfiguration.androidAudioAttributes.flags,
        contentType: currentConfiguration.androidAudioAttributes.contentType,
      ),
    ),
  );
~~~

It is working properly on Android but I am not sure if it is the recommended way and **I have no idea how to do it in ios** with the available options  _avAudioSessionCategory_, _avAudioSessionCategoryOptions_ or _avAudioSessionMode_

Thank you in advance.

**Comment by ryanheise** [comment]
Hi @mmartinalo , the eventual goal is to implement all of the AVAudioSession API but I started with just the features that I personally needed. If you take a look at the source documentation for Apple's [AVAudioSession](https://developer.apple.com/documentation/avfoundation/avaudiosession?language=objc) , perhaps you can identify which features you need, then you can let me know and I can add those features next.

**Comment by mmartinalo** [comment]
Hello @ryanheise ,

I was reading in-depth the documentation and I realized that [AVAudioSession playAndRecord](https://developer.apple.com/documentation/avfoundation/avaudiosession/category/1616568-playandrecord)  category solve my problems:
- plays audio through earpiece
- locks the screen

Both for android and ios the code would be something like
~~~dart
    final session = await AudioSession.instance;
    final AndroidAudioAttributes currentAndroidAttributes = session.configuration.androidAudioAttributes;
    await session.configure(
      session.configuration.copyWith(
        androidAudioAttributes: AndroidAudioAttributes(
          usage: AndroidAudioUsage.voiceCommunication,
          flags: currentAndroidAttributes.flags,
          contentType: currentAndroidAttributes.contentType,
        ),
        avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
      ),
    );
~~~

I think it would be interesting to encapsulate a similar logic in a public function in the AudioPlayer.

Thanks for the support!

**Comment by ryanheise** [comment]
Glad you found a solution. I'd rather have a clear separation of concerns between these two plugins so that audio_session is responsible for switching between devices or detecting when a switch occurs, while just_audio doesn't need to know.

Interestingly, the name "just" audio actually stemmed from a goal to build an audio plugin that didn't take on any other responsibilities besides the audio signal itself, while different plugins could handle settings for the hardware devices, etc.

**Comment by MohsenHaydari** [comment]
> Hello @ryanheise ,
> 
> I was reading in-depth the documentation and I realized that [AVAudioSession playAndRecord](https://developer.apple.com/documentation/avfoundation/avaudiosession/category/1616568-playandrecord) category solve my problems:
> 
> * plays audio through earpiece
> * locks the screen
> 
> Both for android and ios the code would be something like
> 
> ```dart
>     final session = await AudioSession.instance;
>     final AndroidAudioAttributes currentAndroidAttributes = session.configuration.androidAudioAttributes;
>     await session.configure(
>       session.configuration.copyWith(
>         androidAudioAttributes: AndroidAudioAttributes(
>           usage: AndroidAudioUsage.voiceCommunication,
>           flags: currentAndroidAttributes.flags,
>           contentType: currentAndroidAttributes.contentType,
>         ),
>         avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
>       ),
>     );
> ```
> 
> I think it would be interesting to encapsulate a similar logic in a public function in the AudioPlayer.
> 
> Thanks for the support!

thanks , you saved my time :X

**Comment by ryanheise** [comment]
Would you mind sharing your solution on this issue? #37 

The goal of that issue is to provide a convenience method in the `AudioSession` class to handle this common use case in a platform-independent way (while still keeping the native APIs available for more advanced use cases).
